### ISSUE TITLE
Check: NOT PERMITTED Curl

### ISSUE THREAD

**Issue by davidperezgar** [WordPress/plugin-check-legacy#18]
Not permitted curl functions. We have WordPress functions.

**Comment by dd32** [comment]
This is covered by https://github.com/WordPress/plugin-check/blob/54f1eb0142905bf03f80459ea5668d559fad233d/checks/phpcs/plugin-check.xml#L72-L75

`WordPress.WP.AlternativeFunctions.curl_curl_exec`, `WordPress.WP.AlternativeFunctions.curl_curl_init`

The error level is a `warning` however, which should likely be raised to `Error`.
```
<strong>WordPress.WP.AlternativeFunctions.curl_curl_init</strong> Line 5 of file test-plugin/problematic.php.<br>
Using cURL functions is highly discouraged. Use wp_remote_get() instead.<br><pre><code>curl_exec( curl_init( &#039;http://localhost&#039; ) );</code>
```
