### ISSUE TITLE
Check: NOT PERMITTED file_get_contents

### ISSUE THREAD

**Issue by davidperezgar** [WordPress/plugin-check-legacy#19]
Not permitted the use of file_get_contents

**Comment by dd32** [comment]
Covered by `WordPress.WP.AlternativeFunctions` - `WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents`
https://github.com/WordPress/plugin-check/blob/54f1eb0142905bf03f80459ea5668d559fad233d/checks/phpcs/plugin-check.xml#L72C1-L75
