### ISSUE TITLE
Not permitted use of function: wp_create_user

### ISSUE THREAD

**Issue by davidperezgar** [WordPress/plugin-check-legacy#36]
It's not permitted to create users within the plugin.

**Comment by dd32** [comment]
This is covered here: https://github.com/WordPress/plugin-check/blob/46f1caf2ca994105662b68ff8acd8ab6c0a49867/checks/phpcs/plugin-check-needs-review.xml#L43 and unit tested here: https://github.com/WordPress/plugin-check/blob/46f1caf2ca994105662b68ff8acd8ab6c0a49867/tests/checks/test-phpcs-review.php#L29
