### ISSUE TITLE
Check: Stable tag match with Plugin version

### ISSUE THREAD

**Issue by davidperezgar** [WordPress/plugin-check-legacy#41]
This check tests the plugin to use the same version from the Plugin Header to the readme. 
It has to be the same.

**Comment by EvanHerman** [comment]
It looks like this has already been implemented
https://github.com/WordPress/plugin-check/commit/937b03e601c3fed9ea28f6b5f9e0d1b433df3f76

**Comment by davidperezgar** [comment]
You're right. Let's close this issue!
